name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Setup Just
      uses: extractions/setup-just@v1

    - name: Restore dependencies, build, test & distribute using Just
      run: just configuration=${{ matrix.configuration }} distribute

    - name: Upload coverage
      if: ${{ matrix.configuration == 'Release' }}
      uses: codecov/codecov-action@v3
      with:
        directory: ./.coverage
        files: Cobertura.xml
        fail_ci_if_error: true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: TotalMixVC ${{ matrix.configuration }} Setup
        path: artifacts/*.exe
        if-no-files-found: error
